version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ambar_postgres
    environment:
      POSTGRES_DB: abdul
      POSTGRES_USER: abdul
      POSTGRES_PASSWORD: abdul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: ambar_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/abdul
      SPRING_DATASOURCE_USERNAME: abdul
      SPRING_DATASOURCE_PASSWORD: abdul
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    network_mode: host

volumes:
  postgres_data: