version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: no
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel debug
  postgres:
    image: postgres:latest
    container_name: orgolink_postgres
    environment:
      POSTGRES_DB: abdul
      POSTGRES_USER: abdul
      POSTGRES_PASSWORD: abdul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: orgolink_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/abdul
      SPRING_DATASOURCE_USERNAME: abdul
      SPRING_DATASOURCE_PASSWORD: abdul
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      REDIS_HOST: cache
      REDIS_PORT: 6379
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data: